### ISSUE TITLE
migrations/schema.sql and schema_migration table is empty after running migrations

### ISSUE THREAD

**Issue by emurmotol** [gobuffalo/gobuffalo#209]
gobuffalo version
```
λ buffalo version
?[36mINFO?[0m[0000] Buffalo version is: v0.11.0
```

database.yaml

```
development:
  dialect: postgres
  database: myapp_development
  user: postgres
  password: root
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:root@127.0.0.1:5432/myapp_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:root@127.0.0.1:5432/myapp_production?sslmode=disable"}}
```

Before it works fine but, now when I run `buffalo db migrate` the generated file `migrations/schema.sql` is empty and when I check `schema_migration`, the table is also empty.

Does anyone has the same issue?
